server:
  port: 8085

eureka:
  instance:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

    prefer-ip-address: true

spring:
  boot:
    message: Hello, Department Service Spring Cloud Bus Demo

    ################### DATABASE CONFIGURATION #################
  datasource:
    url: jdbc:postgresql://localhost:5433/department_db
    username: koko
    password: password123
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
